### ISSUE TITLE
ar: bin/libaby.a: No such file or directory

### ISSUE THREAD

**Issue by manel1874** [SSGAalto/minionn#1]
Hi, I was trying to run the minionn framework but during compilation I received the following error:

ar: bin/libaby.a: No such file or directory
Makefile:87: recipe for target 'bin/libaby.a' failed
make: *** [bin/libaby.a] Error 1

On the terminal I typed the following:

sudo apt install libssl-dev libgmp-dev libglib2.0-dev
pip install pybind11 cppimport
git clone --recursive https://github.com/SSGAalto/minionn
cd minionn/lib
make all

After some compilation, the file ABY/bin/libaby.a was not found. In fact on this directory ABY/bin there is just the circ folder.

Am I missing something?

Any help is appreciated,
Manuel

**Comment by fritzalder** [comment]
Hi,
that was an error on my part, I never ran the Makefile on an empty directory and forgot to create the bin directory on a fresh install...
I fixed this in 27b92976e6080b8247e08a3509cb6cb16c6c3d5f and also just pushed a new version that is compatible with the current version of SEAL.

Feel free to open another Issue if the problem remains or if you have questions.
Cheers,
Fritz
