### ISSUE TITLE
an error at "python test.py"

### ISSUE THREAD

**Issue by youlda** [SSGAalto/minionn#9]
i got an error as: 
/minionn/lib/minionnCrypto.cpp:18:1: error: ‘PolyCRTBuilder’ does not name a type
 PolyCRTBuilder *crtbuilder;
 ^~~~~~~~~~~~~~
/minionn/lib/minionnCrypto.cpp: In function ‘void init(int)’:
/minionn/lib/minionnCrypto.cpp:25:24: error: no matching function for call to ‘seal::EncryptionParameters::EncryptionParameters()’
   EncryptionParameters parms;
i think it is because now the version SEAL2.3.1 is no longer used, and even the earliest SEAL3.1.0 has changed some functions. What could i do to make it work again? maybe a version SEAL2.3.1,  but i cannot find it.

**Comment by oahcnauygnid** [comment]
ohh, luckily, i got a SEAL2.3.1, but it still has another error:
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    m = cppimport.imp("minionn")
  File "/lib/python3.7/site-packages/cppimport/importer.py", line 56, in imp
    return __import__(fullname)
ImportError: /minionn/lib/minionn.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN4seal4util16global_variables25default_coeff_modulus_192E

**Comment by youlda** [comment]
ohh, luckily, i got the SEAL2.3.1, now i can do "python test.py" without errors.
